# Site settings
title: "Mario Jimenez Illesca"
description: "CS Student · Developer · Portfolio"
url: "https://nochinxx.github.io"  # update with your username

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social handles (optional)
github_username: nochinxx
linkedin: https://www.linkedin.com/in/mario-jimenez-7b9683206/
email: mariojillesca@gmail.com
